### ISSUE TITLE
what this plugin do ?

### ISSUE THREAD

**Issue by techmastersofficial** [RationalCoding/multihack-brackets#1]
i test this but nothing happen

**Comment by t-mullen** [comment]
If two (or more) Brackets users enter the same RoomID and have the same initial project open, the projects will be synced.

It won't do anything if no one else is in your room. Try it with a friend or with another copy of Brackets running.

**Comment by t-mullen** [comment]
Updated the README to be a bit clearer.

**Comment by techmastersofficial** [comment]
Ok i got it (y) Thanks
