### ISSUE TITLE
Fetch code only syncs file names

### ISSUE THREAD

**Issue by mariansauter** [RationalCoding/multihack-brackets#10]
The Fetch Code function to fetch the initial code only catches the file names but the files are empty. (fetc Code works in multihack web)

**Comment by t-mullen** [comment]
Hi @mariansauter! I'll look into this.

Are you fetching from web-->brackets or brackets-->brackets?

**Comment by mariansauter** [comment]
Hi! Getting code

brackets --> web 
works perfectly fine but

brackets -->brackets
does not work

**Comment by t-mullen** [comment]
Files were being stored in Bracket's internal memory instead of being written to disk.

Update and everything should work.
