### ISSUE TITLE
Show how many people are in the current room

### ISSUE THREAD

**Issue by tweakimp** [RationalCoding/multihack-brackets#11]
I think it would be a great addition if the multihack icon on the right showed how many people are in the current room. 
Maybe even extend this idea and give the option to give yourself a nickname when you join a room so the overview shows not only that other people are there, but also who.

**Comment by t-mullen** [comment]
This is a great idea. The nicknames too. I'll add this to the queue, thanks! :+1:

**Comment by tweakimp** [comment]
Great! :)

**Comment by tweakimp** [comment]
Dont forget to make it possible to choose from whom to fetch the code ;)

**Comment by t-mullen** [comment]
Implemented this as a interesting graph showing the peer connections. **v3.1.0**

Will add the ability to fetch from a chosen peer in a later version!
