### ISSUE TITLE
Give the option to fetch code directly from a github repository 

### ISSUE THREAD

**Issue by tweakimp** [RationalCoding/multihack-brackets#12]
I would welcome the possiblity to make a github repository the client from which to fetch code from and even save to.

Maybe that is too far from the general idea of this plugin, just a random thought.

**Comment by t-mullen** [comment]
Yeah, that's really useful as a collaboration tool, but I think it might be better suited as a separate extension.

Have you tried any of these? http://blog.brackets.io/2013/07/26/using-github-with-brackets/?lang=en

**Comment by tweakimp** [comment]
I have looked at them, but they didnt give me what I want: a one button solution to load from and merge to github.

**Comment by t-mullen** [comment]
This is definitely a good idea. Maybe I'll make it in the future, but right now I have plenty of projects!

Maybe give it a try yourself? Brackets can always use more extension developers! :)

**Comment by tweakimp** [comment]
I am just starting to learn JS and about to finish my first project, a simple jump and run game. I dont think Im ready to code something like that, I can just bring in new ideas :)

**Comment by t-mullen** [comment]
No problem, maybe one day! :)
