### ISSUE TITLE
Support Linux Mint (and other builds without WebRTC)

### ISSUE THREAD

**Issue by AonoZan** [RationalCoding/multihack-brackets#13]
Not sure what Im doing wrong but after todays update I cant create room.I get message when i hit button to join room. What is meant by "your browser", brackets editor or real browser? Im almost sure that both of them are up to date. (but there is possibility that im missing something installed)

**Comment by t-mullen** [comment]
What version of brackets do you have?

**Comment by t-mullen** [comment]
Updating Brackets will fix your issue, but please post your version first so I can identify which versions are unsupported.

Unfortunately I can't support old versions of Brackets since they don't have the needed technologies for the new P2P protocol.

**Comment by t-mullen** [comment]
The new brackets is much more stable anyways. No reason not to update.

**Comment by AonoZan** [comment]
Yesterday when I posted issue a have had older brackets (1.9) and it showed "Latest version" when you do the "Check for update". So I believed that I have latest version.
Now I have updated to the "1.10 experimental build 1.10.0-17348" which you can find in "Other downloads" section at their site.
Issue is stil present.

![image](https://cloud.githubusercontent.com/assets/7921470/24963430/d8a7c644-1f9e-11e7-8f86-4068bbd262b3.png)

![image](https://cloud.githubusercontent.com/assets/7921470/24963460/f161a970-1f9e-11e7-9d6e-b444a1c316d7.png)

**Comment by AonoZan** [comment]
Also sorry for late reply. It was not intentional. Best regards and I love your work :)

**Comment by t-mullen** [comment]
1.9 is my version as well, so something else is happening here. I'll look into it.

**Comment by t-mullen** [comment]
I couldn't reproduce on any of my machines. :/
Can you post your operating system and try this quick test for me:

1. Go to "Debug > Reload Brackets without Extensions"
2. When it reloads, do "Debug > Show Developer Tools"
3. In the console, type `webkitRTCPeerConnection` and let me know what it prints.

Thanks, hope we can fix this.

**Comment by AonoZan** [comment]
Ok.
OS: Linux Mint 18 Sarah (4.4.0-21-generic)
Browser: Opera 44 (latest)

When reloaded I cant just simply click open Dev tools. I think I can use this link http://localhost:9234 to load Dev tools in Opera. Then going simply to the console and typing didnt work. When I "Inspect" that window and type that string I get folowing code:
function RTCPeerConnection() { [native code] }


![image](https://cloud.githubusercontent.com/assets/7921470/24971468/683f0ab0-1fb8-11e7-9652-e5ed0c0de401.png)

Hope it helps. I haven't debugged Brackets and to be honest Im fairly new to Brackets.

**Comment by t-mullen** [comment]
Thanks, I'll try to get a Mint VM running to see if it's OS-specific. This issue isn't related to your browser or Opera, just Brackets.

I didn't know about the CEF remote debugger, very cool. I noticed you can't run commands though.

Does it suggest `webkitRTCPeerConnection` when you type `webkitRTC`? (Not in the inspector, at http://localhost:9234)

**Comment by AonoZan** [comment]
![image](https://cloud.githubusercontent.com/assets/7921470/24976003/0f900eae-1fc8-11e7-903a-1bd575a2dda7.png)

Heres what are the suggestions.

**Comment by t-mullen** [comment]
Ok, so webRTC is definitely missing from your Brackets build. This is wrong, I just need to find out why.

**Comment by t-mullen** [comment]
It looks like the Linux Mint CEF build is missing some features (namely WebRTC). This is a huge bummer...

I'm going to add a fallback to socket forwarding for Mint. Might take a few days.

**Comment by t-mullen** [comment]
This wasn't as hard as I thought. **3.2.0** has a server forwarding fallback. :)

Works on my phone now too, which is sorta cool.

Let me know if you experience any issues. Note that there is a limit on the public server for server forwarding. (5mb project size for "fetch code") I have to do this to prevent people from choking the server while sending enormous projects.

**Comment by AonoZan** [comment]
It works like a charm. I love particles.js animation that shows people connected. :)

**Comment by t-mullen** [comment]
Great!

It's this awesome repo: https://github.com/feross/p2p-graph

**Comment by AonoZan** [comment]
Oh. I have assumed its particles.js library. Great thanks!
