### ISSUE TITLE
Allow users to choose who to fetch code from

### ISSUE THREAD

**Issue by t-mullen** [RationalCoding/multihack-brackets#14]
Suggested by @tweakimp

**Comment by Worie** [comment]
I guess that's pretty important one

**Comment by t-mullen** [comment]
@tweakimp, I like your "master peer" idea. It seems simpler than trying to keep everyone in sync when everyone is sharing code, plus it makes desync prevention easier if there's one absolute project version.

**Comment by tweakimp** [comment]
Maybe it's the solution to both this and the "highlight" problem.

**Comment by t-mullen** [comment]
This isn't needed anymore with the upcoming YJS integration. All users will always have the same code, so "Fetch Code" is being removed entirely!
