### ISSUE TITLE
Automatically check for desyncs

### ISSUE THREAD

**Issue by tweakimp** [RationalCoding/multihack-brackets#16]
It's me again!
(Are you even open for more issues from me? ;)
Sometimes when I code with my friend, we get desynced. I cant really tell when this happens, we assume it starts when multiple users do huge changes at the same time, like pasting multiple lines of code or appling extensions like a beautifier. 
What I thought of now: maybe it would be a good idea to have an auto re-sync feature. One user can be assigned as the master via the room interface and when an auto re-sync happens, all other users will change their code to the master code. Just like key frames in video encryption, this would make it more stable in my totally unprofessionall opinion.

**Comment by t-mullen** [comment]
Always open to issue from anyone!

Does "Fetch Code" not do this? It's meant for resync too. Did you mean some kind of automatic resyncing?

I just fixed an issue that would stop all syncs when doing a large paste. Try updating and let me know if you still get desynced often.

Desyncs should be rare if everything is working as intended.

**Comment by tweakimp** [comment]
Yes, fetch code is the manual version of what I suggest to be automated.
We will keep an eye on that, thanks.

**Comment by t-mullen** [comment]
Ideally things would rarely (if ever) desync, so hopefully we won't need to check for desyncs automatically. I'll think about it though, it's a good idea.

**Comment by tweakimp** [comment]
Maybe think of it as a safety precaution. If the code desynces more rarely, it's harder to notice.

**Comment by t-mullen** [comment]
YJS will handle all syncing in the future, so this won't be needed.

Desyncs will be mathematically impossible, not just rare. :)
