### ISSUE TITLE
Code gets unfolded when other users change something in it

### ISSUE THREAD

**Issue by tweakimp** [RationalCoding/multihack-brackets#17]
I am using
https://github.com/brackets-beautify/brackets-beautify
and enabled "format on save". My friend has code folded. Now when I save (to save and format) all his folds get unfolded. I don't know whether it's the saving or the changes by the extension.

**Comment by t-mullen** [comment]
Code probably unfolds on wholesale changes. I'll see what I can do.

**Comment by RationalCoding** [comment]
I assume you're using this extension? https://github.com/thehogfather/brackets-code-folding

Brackets doesn't have any native code folding, so I'll probably have to pick an extension to support and this is the most popular.

**Comment by RationalCoding** [comment]
TBH I have no clue how to fold code in Brackets. Is it an extension?

**Comment by RationalCoding** [comment]
Nevermind, I see now!

**Comment by t-mullen** [comment]
Doesn't seem to be any way to fix this on my end. When you beautify, all that folding metadata is discarded: https://github.com/brackets-beautify/brackets-beautify/pull/203/files

I don't think Codemirror even allows me to maintain folds on wholesale changes. :/

I'll reopen if something changes.

**Comment by t-mullen** [comment]
I now think it might be possible.

**Comment by t-mullen** [comment]
Ah, I remember why I closed this now. Beautify itself unfolds the code and removes the metadata. It's nothing to do with Multihack.

I think I can prevent code from unfolding during normal editing though.

**Comment by t-mullen** [comment]
Closing in favour of #40, since this is expressly related to Beautify, which I can't fix.
