### ISSUE TITLE
Selecting text bug

### ISSUE THREAD

**Issue by Frankusky** [RationalCoding/multihack-brackets#19]
Selecting text with ctrl+shift+right arrow bugs when I have your extension enabled, this only happens with the right arrow, left arrow still working as expected

![Extension enabled](http://i.imgur.com/iGbNg15.gif)
![Extension disabled](http://i.imgur.com/D8aL17a.gif)

**Comment by t-mullen** [comment]
Weird, seems listening for selection changes is changing how that behaves.

Looks like a Codemirror bug, I'll see what they think.

**Comment by t-mullen** [comment]
Fixed in 3.4.3

Thanks for the helpful GIFs!

**Comment by Frankusky** [comment]
Wow so fast, thanks! :+1:
