### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by tweakimp** [RationalCoding/multihack-brackets#21]
Are you planning to add other languages? I could write and maintain the german language file, maybe with [poedit](https://poedit.net)

**Comment by t-mullen** [comment]
I have no plans for translation, but any PRs that add it are welcome.

There's not much text, so I don't think it would be too difficult to do manually.

**Comment by RationalCoding** [comment]
Brackets has built-in support for this: https://github.com/adobe/brackets/tree/master/src/extensions/samples/LocalizationExample

**Comment by t-mullen** [comment]
Going to backlog this until the VSCode and Atom versions are finished. If we're going to add localization, we should do it correctly and consistently.

Any temporary language PRs for this version are still welcome, just make them easy-ish to revert if needed.

Of course, you can fork the project and change the strings to German as a quick fix.

**Comment by tweakimp** [comment]
Ok.
I like how you are saying "we" while you do all the work :) 
Prioritizing is important,of course, but it's also a question of where are you want to go with this plugin. Do you want it to be the ultimate pair progtamming tool or to just do what it does now: synchronized coding?

**Comment by t-mullen** [comment]
This will be important for the initial release, but I'm more focused on the core featureset for all the editors right now :)

**Comment by tweakimp** [comment]
ok :) just summon me and ill translate everything to german

**Comment by Worie** [comment]
Feel free to mention me for Polish

**Comment by AonoZan** [comment]
Simple menu items wont be much of a problem for anyone to translate I guess. But if you ever run into need for translating help file, tool-tips etc. you have me for Bosnian. :)

**Comment by t-mullen** [comment]
I've never tried to internationalize software before, so please let me know if this approach won't work:

A json file for each language with this format:
```en.json```
```javascript
{
   "disconnect": "Your connection to \"{{nickname}}\" has been lost.",
   "id_prompt": "Enter the ID of the room you want to join.",
   ... and so on
}
```

Each language file would just swap out these values, while keeping the keys and tags the same (like `id_prompt` and `{{nickname}}`). Any objections?

**Comment by tweakimp** [comment]
Please add a comment to each translation. It's helpful to know where it belongs to.

**Comment by tweakimp** [comment]
Little missclick :)

**Comment by t-mullen** [comment]
Ok, I pushed a translation file. Please add the 2-letter language code and all of the necessary translations. I think they are pretty straightforward, but if anything is unclear, let me know.

There's about 44 different words/phrases that need translation.

**Comment by RationalCoding** [comment]
Also test that the locale is detected correctly in both web and brackets.

**Comment by t-mullen** [comment]
https://github.com/RationalCoding/multihack-brackets/blob/master/lib/lang/translations.json

**Comment by t-mullen** [comment]
@Worie @AonoZan Mentioning for additional translations, when you get the time :)

**Comment by tweakimp** [comment]
I mixed formal and informal adress of the User. I would like to clean that up. Which one do I use?

**Comment by Worie** [comment]
Lets split the translations to separate files (de.json, pl.json and so on). 

Itll prevent a lot of conflicts and be easier to manage. Ill sit to pl translations when  im back from jsconf

**Comment by t-mullen** [comment]
I'd say the solution implemented is adequate for now. Closing as completed.

Splitting up files means determining the language at load time, something I haven't figured out yet (besides simply loading every file). Maybe I'll revisit that, but it should be OK as is.
