### ISSUE TITLE
Polish Diacritical issue 

### ISSUE THREAD

**Issue by Worie** [RationalCoding/multihack-brackets#24]
Typing polish diacritical causes the peer who recieves it to lose connection with the one who sent it. The reciever can no longer get any updates from the peer who sent the diacritical letter (he can communicate with other peers, though)

I guess there's an overall encoding issue somewhere, Brackets DevTools shows: `Uncaught SyntaxError: Unexpected string at index.html:1`

I hadn't any ideas on the Issue name, please rename it to something that fits better when we know what is the real problem.

**Comment by t-mullen** [comment]
Can you post the diacritical that causes this, so I can reproduce?

**Comment by Worie** [comment]
It happened on `ś` in my case, haven't tested the rest: `śćźżńłóąńę`

**Comment by tweakimp** [comment]
Please also test special german letters `ä`,`ö`,`ü` and `ß`.

**Comment by t-mullen** [comment]
Ah, I know what this is. Diacriticals don't increase character length, which I was wrongly assuming was the same as byte length. This should be fixed in the next major version.

**Comment by t-mullen** [comment]
Yes, that was the issue.
