### ISSUE TITLE
Undefined is not a function on Line 93

### ISSUE THREAD

**Issue by AonoZan** [RationalCoding/multihack-brackets#29]
When I try to connect with username and nickname nothing happens. If I inspect in developer tools line 93 in main.js gives error(Uncaught TypeError: undefined is not a function). It involves multihack-core.js. 

My system is Linux Mint 18 with latest updates.

**Comment by t-mullen** [comment]
Probably something to do with the socket fallback. I'll take a look.

**Comment by t-mullen** [comment]
Can you post the full stack trace?

**Comment by AonoZan** [comment]
Theres bunch of bracket errors but few from multihack:

Click main.js:34
handleStart main.js:88
AonoZanRoom Guest main.js:90
Uncaught TypeError: undefined is not a function main.js:93

**Comment by t-mullen** [comment]
Do you have the newest version? 4.1.1?

**Comment by AonoZan** [comment]
Now I have noticed something else.. It doesnt accept nickname. It should at least print "AonoZanRoom AonoZanNick"

Kernel version? No. Still at "4.4.0-21-generic"

**Comment by t-mullen** [comment]
No, multihack-brackets version.

**Comment by AonoZan** [comment]
Probably not. Sorry about this then. Its my fault. Ill update soon. :)

**Comment by t-mullen** [comment]
Well reopen if it still errors after updating. I couldn't reproduce, but there might still be some issue.

**Comment by AonoZan** [comment]
Ok, so everything is up to date but bug persist. (was traveling sorry for late reply)

**Comment by t-mullen** [comment]
The fallback works fine for me, so I'll need some more information:

Does the room ID/nickname modal close when you press join?
Does the icon symbol change to blue?
Does Brackets freeze and/or crash?
Is someone else in the room? If yes, can you try joining an empty room.
Does it work if you don't provide a nickname?
Is there a project open? If yes, can you try it with an empty folder open.

**Comment by AonoZan** [comment]
Room modal closes when I try to connect.
Icon doesnt change to blue.
Brackets is just fine
Room is not yet created, Im creating room (empty).
It doesnt work with no nickname (in fact it doesnt accept nickname typed or not it will always try to connect as guest)
I tryed with empty and all kinds of projects.

**Comment by t-mullen** [comment]
Ok, thanks for the info.

How do you know it's trying to connect as "Guest"?

**Comment by AonoZan** [comment]
Well there are your console log statements that print name of the room and nickname. So at the point of logging name is still at default.

**Comment by t-mullen** [comment]
Ok, so there seems to be some kind of module loading error. I think there might be some other errors., could you copy-paste your entire dev console log (with backticks "`" so it formats right). Thanks.

**Comment by AonoZan** [comment]
![image](https://cloud.githubusercontent.com/assets/7921470/26031419/d4554836-3872-11e7-8add-2559e667940e.png)

Will this screenshot do?

All the other extensions are disabled and bracket reloaded. Just one attempt in multihack of connecting with "Roomtest" and "Roomnick".

I havent noticed that 21489 line showing up before...

**Comment by t-mullen** [comment]
Yeah, that first error is the cause. Really strange error, but it probably has something to do with ES6 support in the old CEF version that Linux Mint Brackets uses.

**Comment by t-mullen** [comment]
I transpiled all the ES6. Try `4.1.3` and let me know if the problem goes away (it should, or there are other problems).

**Comment by AonoZan** [comment]
Ok Im in able to connect. Issue of not picking my nickname and always adding me as a Guest persist.

**Comment by t-mullen** [comment]
So aside from nickname always being "Guest", everything works?

**Comment by AonoZan** [comment]
No! I just realised that couple of problems happen.

When I connect to room that I have connected to from another editor I get content synced but that one original and first gets it code duplicated.

When I leave room me ("Guest", user that have connected) stays connected to the server.

You could basically Connect to the room disconnect few times and get all those connection open.

**Comment by AonoZan** [comment]
Theres one more weird bug. I have closed editor and opened it again, named new room name and connected. Disconnected after, connected again and had my code synced with previous project look.
Procedure:

Created project "test"
Created file and added content
Connected to the server (and few more time from other editor or same)
Disconected everything and closed
Opened project again
Changed file to new look **(edit: file was not saved here so that might have led to reseting which is maybe ok)**
Connected again
Disconnected and connected once more just to see that my code is synced to exact look last time I closed everything.

**Comment by t-mullen** [comment]
It might have been the file not being saved, but I can understand why that might not have worked. Basically what you're trying to do is sync two different copies of the same file. Obviously you can't do this, so Multihack chooses one at random.

Multihack has no way of knowing which version is the "correct" version. All it knows is that you want to sync files. We could add a feature to set the "master" code, but honestly if you're merging conflicts, you should use a real version control, like Git.

I've said before that Multihack is NOT a replacement for Git. It's for working on the same copies of projects. The fact you can send code over it is just an added bonus for convenience.

I'll try to see why nicknames aren't working for you. :)

**Comment by t-mullen** [comment]
Nicknames fixed in `4.1.4`

**Comment by AonoZan** [comment]
Works like charm! Thank you.
