### ISSUE TITLE
Initial code sync

### ISSUE THREAD

**Issue by AonoZan** [RationalCoding/multihack-brackets#3]
That initial code sync feature is needed so much. I have tried your plug in today and I love it so much. The fact that me and my friend can have real-time code sync and immediate preview in browser window is such a useful feature. I have to say that I have lost sync at some point somehow. I appreciate your work. Thank you :+1:

**Comment by t-mullen** [comment]
I agree! The old web version had it, so I have an idea how to implement it.

The only problem is sending large files over websockets. This project will probably be switching to pure WebRTC soon, so no problem there.

Thanks for trying it out!

**Comment by t-mullen** [comment]
Added the option to fetch code from the other person. It should solve this issue and help with any desync problems.

Some limitations:
- I had to put a max of 20mb and 1000 files to prevent abuse, but this limit is lifted if you are running your own server. (Should be gone when we move to full P2P)
- Large projects send slowly and will probably crash the web version.

Let me know how it works for you. Feedback always appreciated.

**Comment by AonoZan** [comment]
Thank you so much. I will take some time to test it and report back if I spot something that could be useful to you.

**Comment by t-mullen** [comment]
There was a small bug that might have caused it to now work for you. Did a few more tests and it should be fine now.

**Comment by AonoZan** [comment]
![image](https://cloud.githubusercontent.com/assets/7921470/24839718/27a61778-1d60-11e7-8c2e-fff433a84811.png)

Heres what happens on Linux Mint. Im not sure if its bug or maybe I need some dependencies for it to work. I did monitored disk IO writes and also network usage. It seems to me that code has been sent and downloaded (one and then second operation). No IO operation was made during sync. Did few lines write/save just to confirm that both editors are in sync but code fetch never fetched first line that was written before room is created.

**Comment by t-mullen** [comment]
Yeah, I'm looking into that right now. See #10

**Comment by t-mullen** [comment]
@AonoZan It's fixed (if you weren't following that issue.)
