### ISSUE TITLE
Choose files to sync

### ISSUE THREAD

**Issue by siphomateke** [RationalCoding/multihack-brackets#38]
This is a feature request.

Could a button or option be added to only sync certain files rather than the whole working directory? This would be useful because sometimes when connecting a new computer to multihack-server, files that were previously synced but no longer exist get downloaded to all the computers.

**Comment by t-mullen** [comment]
This is a form of version control, something I'm not interested in adding to Multihack.

Although it seems like a good idea, the proper way to work with two different versions of a project is through version control software like Git or Subversion. Multihack isn't version control, it's for remote pair programming on a single version.

The fact that Multihack works with two different versions is just a side effect of the syncing, and will merge conflicts in unpredictable ways (as you've already seen with files always being added if they do not exist). The alternative would be throwing an error if the versions didn't match, which I thought was too strict.

Commit and merge your offline changes with Git, then pair on a single, shared version.

**Comment by siphomateke** [comment]
@RationalCoding Fair point I just thought it might help with the apparent bugginess. I will use git instead.
