### ISSUE TITLE
Hostname preference requires protocol and no path

### ISSUE THREAD

**Issue by siphomateke** [RationalCoding/multihack-brackets#39]
**Issue**
Unable to edit an already existing file after connecting to multihack-server. Additionally if a new file is created and you try typing it will duplicate the text and behave strangely.

**Steps to reproduce**

1. Open an empty folder in brackets
2. Add a .brackets.json file with the following:
`{
    "multihack-brackets.lastRoom": "test",
    "multihack-brackets.hostname": "localhost:6001/"
}`
3. Start a multihack-server on the same computer
4. Connect to the multihack-server from brackets leaving the settings as default (the room id is set by .brackets.json and the nickname is left blank)
5. Try to select, type or otherwise edit text in .brackets.json
6. Create a new file test.js
7. Try typing anything in test.js

**Expected Result**
You should be able to edit .brackets.json and if you create a new file you should be able to type normally into it.

**Comment by t-mullen** [comment]
Socket.io demands a protocol in the hostname, and doesn't accept paths.

Your .brackets.json should be:
`{ "multihack-brackets.lastRoom": "test", "multihack-brackets.hostname": "http://localhost:6001" }`

If you're using SSL, use https instead.

I know, it's annoying. I'll try to make it a bit more robust.

**Comment by t-mullen** [comment]
I added a note to the README for multihack-server. I think that will suffice.
